version: '3.7'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: symfony

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - "discovery.type=single-node"

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025

volumes:
  postgres_data:
