version: '3.7'

services:

  app:
    user: "${UID}:${GID}"
    image: sfx:0.1
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    expose:
      - 9000
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - COMPOSER_CACHE_DIR=/tmp/
    volumes:
      - ./:/var/www/app/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - sf-net

  nginx:
    image: nginxinc/nginx-unprivileged:stable
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ".:/var/www/app/"
      - ".docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - sf-net
    depends_on:
      - app

  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_USER: ${POSTGRES_USER:-test}
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - sf-net
    ports:
      - "19193:5432"

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025

networks:
  sf-net:

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
